version: '3.8'

services:
  # Official Backstage
  backstage:
    image: backstage/backstage:latest
    ports:
      - "7007:7007"
    volumes:
      - ./helm-values/backstage-values.yaml:/app/app-config.yaml
      - ./backstage-templates:/app/templates
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
      POSTGRES_DB: backstage

  # MLflow for Model Registry
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db

  # ArgoCD
  argocd:
    image: quay.io/argoproj/argocd:latest
    ports:
      - "8080:8080"
    command: ["argocd-server", "--insecure"]

  # Custom GPU Cost Tracker
  gpu-cost-tracker:
    build: ./custom-services/gpu-cost-tracker
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

networks:
  default:
    name: devportal-network