app:
  title: AI Developer Platform
  baseUrl: http://localhost:7007

organization:
  name: Platform Engineering Team

backend:
  baseUrl: http://localhost:7007
  database:
    client: pg
    connection:
      host: postgres
      port: 5432
      user: backstage
      password: backstage

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

kubernetes:
  clusterLocatorMethods:
    - type: config
      clusters:
        - name: ai-platform
          url: ${KUBERNETES_API_URL}
          authProvider: serviceAccount

aiPlatform:
  mlflow:
    url: http://mlflow:5000
  costTracker:
    url: http://gpu-cost-tracker:3000