name: Validate & Security Scan

on:
  pull_request:
    branches: [main]
  push:
    branches: [develop]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload Security Results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
  
  validate-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Format Check
        working-directory: ./terraform
        run: terraform fmt -check
      
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -backend=false
      
      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate